### ISSUE TITLE
What's res.json(news) in the example of the code?

### ISSUE THREAD

**Issue by zeromero-dev** [yashkathe/Download-ComicBooks-API#2]
I've tried your example of code to see how it works and don't get what the line with ```res.json(news)``` stands for?
Also while running this code with express "^4.18.1" i get **promised failed on first** error.
```
const comicsApi = require("comicbooks-api");
const express = require("express");
const app = express();

app.get("/", async (req, res) => {
  const comics = await comicsApi.getLatestComics(1);
  res.json();
});

app.listen(5050);
```

**Comment by yashkathe** [comment]
- res.json()
 res.json() is just to convert the javascript object into JSON 
and 
the example had a mistake it should be res.json(comics)  
or you can simply just console.log(comics)

-  promised failed on first 
This was just a error handling code I had  added during development and forgot to remove. Anyways, I have also solved this error.

**Comment by yashkathe** [comment]
I have published the latest version of package.    
Upgrade it and try again

**Comment by zeromero-dev** [comment]
Yup great, it works now!

**Comment by zeromero-dev** [comment]
By the way, will there be an option to actually download the comics instead of [Object] dummy?
